### ISSUE TITLE
materialTheme in MainWindow

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-gui#42] opened 2019-05-30 05:21 UTC
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/42)) by mingfei sun (Bitbucket: [mingfeisun](https://bitbucket.org/%7B1e5a944b-56e4-4808-b81d-d6de318feadc%7D/)).**

----------------------------------------
It seems that the material theme for the main window is “Light”, which may cause the visibility issues. See

[https://github.com/ignitionrobotics/ign-gui/blob/2dd4f0bf9bbcd90399ecbecddfe5a8cf46aa9f73/src/MainWindow.cc#L428](https://github.com/ignitionrobotics/ign-gui/blob/2dd4f0bf9bbcd90399ecbecddfe5a8cf46aa9f73/src/MainWindow.cc#L428)

The visibility problems when displaying ign gazebo in Ubuntu Bionic:

![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/64K5zaR/images/2895942737-ign-gazebo-3.png)
![](https://osrf-migration.github.io/ignition-gh-pages/data/bitbucket.org/repo/64K5zaR/images/564858121-ign-gazebo-2.png)
‌

‌

I temporally changed the code as follows: this-&amp;gt;materialTheme = “Dark”; after recompiling, it works ok. But it’s not flexible. May I ask if there are any solutions to solve this problem?

**Comment by chapulina** [comment] 2020-10-17 17:25
I can't reproduce this issue. I'll close it for now. If someone can reproduce it again please speak up and we can reopen the issue.

**Closed by chapulina** 2020-10-17 17:25 UTC
Labels: enhancement
